version: "3.9"

services:
  java_app:
    container_name: java_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JAR_FILE=target/*.jar
      - AIR_QUALITY_API_TOKEN=${AIR_QUALITY_API_TOKEN}
    depends_on:
      - java_db
    networks:
      - java_network

  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
      - ./db:/db
    networks:
      - java_network
volumes:
  pgdata: {}

networks:
  java_network:
